import axios from "axios";
import Producto from "../models/ProductModel.js";

const cargarProductosWP = async (req, res) => {
  let { data } = [
  {
    id: 12316,
    name: "Maquillaje y peinado",
    slug: "maquillaje-y-peinado",
    permalink: "https://calyaan.com/producto/maquillaje-y-peinado/",
    date_created: "2023-05-12T12:00:59",
    date_created_gmt: "2023-05-12T17:00:59",
    date_modified: "2023-05-12T12:01:55",
    date_modified_gmt: "2023-05-12T17:01:55",
    type: "simple",
    status: "publish",
    featured: false,
    catalog_visibility: "visible",
    description:
      "<p>El maquillaje y peinado pretende destacar tu belleza y facciones de acuerdo al evento y al look que vas a usar.</p>\n<p>El peinado recogido despeja la cara, nos mantiene fresca, tienen cierto aire de sofisticaci\u00f3n\u2026 son muchos los motivos por los que amamos los recogidos.</p>\n<p>Esta vez, ponemos el foco en aquellos que no requieren habilidades extraordinarias, que se pueden crear en pocos minutos y con pocos elementos.</p>\n<p>Hablamos de los peinados recogidos f\u00e1ciles, esos que pueden usarse a diario y que solo esta a un click o whatsapp de distancia.</p>\n<p>&nbsp;</p>\n",
    short_description:
      "<p>Maquillaje y peinado pretende destacar tu belleza y tus facciones de acuerdo al evento y al look que vayas a usar.</p>\n<p>El peinado recogido despeja la cara, nos mantiene fresca, tienen cierto aire de sofisticaci\u00f3n\u2026 son muchos los motivos por los que amamos los recogidos.</p>\n<p>Esta vez, ponemos el foco en aquellos que no requieren habilidades extraordinarias, que se pueden crear en pocos minutos y con pocos elementos.</p>\n<p>Hablamos de los peinados recogidos f\u00e1ciles, esos que pueden usarse a diario y que solo esta a un click o whatsapp de distancia.</p>\n",
    sku: "",
    price: "260000",
    regular_price: "299000",
    sale_price: "260000",
    date_on_sale_from: null,
    date_on_sale_from_gmt: null,
    date_on_sale_to: null,
    date_on_sale_to_gmt: null,
    on_sale: true,
    purchasable: true,
    total_sales: 0,
    virtual: false,
    downloadable: false,
    downloads: [],
    download_limit: -1,
    download_expiry: -1,
    external_url: "",
    button_text: "",
    tax_status: "taxable",
    tax_class: "",
    manage_stock: false,
    stock_quantity: null,
    backorders: "no",
    backorders_allowed: false,
    backordered: false,
    low_stock_amount: null,
    sold_individually: false,
    weight: "",
    dimensions: { length: "", width: "", height: "" },
    shipping_required: true,
    shipping_taxable: true,
    shipping_class: "",
    shipping_class_id: 0,
    reviews_allowed: true,
    average_rating: "0.00",
    rating_count: 0,
    upsell_ids: [],
    cross_sell_ids: [],
    parent_id: 0,
    purchase_note: "",
    categories: [
      { id: 31, name: "Centro de belleza", slug: "centro-belleza-bogota" },
      { id: 82, name: "Maquillaje en bogota", slug: "maquillaje-en-bogota" },
    ],
    tags: [],
    images: [
      {
        id: 6003,
        date_created: "2022-04-05T03:49:40",
        date_created_gmt: "2022-04-05T13:49:40",
        date_modified: "2022-09-16T04:43:52",
        date_modified_gmt: "2022-09-16T14:43:52",
        src: "https://calyaan.com/wp-content/uploads/2022/03/8AC3956-scaled.jpg",
        name: "_8AC3956",
        alt: "Maquillaje y peinado social",
      },
    ],
    attributes: [],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 59,
    price_html:
      '<del aria-hidden="true"><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>299.000</bdi></span></del> <ins><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>260.000</bdi></span></ins>',
    related_ids: [861, 830, 795, 799, 864],
    meta_data: [
      { id: 110313, key: "rank_math_internal_links_processed", value: "1" },
      { id: 110333, key: "_wa_order_phone_number", value: "numero de calyaan" },
      { id: 110334, key: "_wa_order_button_text", value: "" },
      { id: 110335, key: "_wa_order_custom_message", value: "" },
      { id: 110336, key: "_hide_wa_button", value: "no" },
      { id: 110337, key: "_hide_atc_button", value: "no" },
      { id: 110338, key: "_force_show_atc_button", value: "no" },
      { id: 110339, key: "site-sidebar-layout", value: "default" },
      { id: 110340, key: "site-content-layout", value: "default" },
      { id: 110341, key: "theme-transparent-header-meta", value: "default" },
      { id: 110342, key: "stick-header-meta", value: "default" },
      { id: 110343, key: "_yoast_wpseo_primary_product_cat", value: "31" },
      { id: 110344, key: "_yoast_wpseo_content_score", value: "90" },
      {
        id: 110345,
        key: "_yoast_wpseo_estimated-reading-time-minutes",
        value: "1",
      },
      { id: 110346, key: "_product_meta_id", value: "0" },
      { id: 110347, key: "_wc_facebook_sync_enabled", value: "yes" },
      { id: 110348, key: "fb_visibility", value: "yes" },
      { id: 110349, key: "fb_product_description", value: "" },
      {
        id: 110350,
        key: "_wc_facebook_product_image_source",
        value: "product",
      },
      { id: 110351, key: "_wc_facebook_commerce_enabled", value: "no" },
      { id: 110352, key: "fb_product_group_id", value: "4997538460342741" },
      { id: 110353, key: "fb_product_item_id", value: "4997538477009406" },
      {
        id: 110354,
        key: "_yoast_wpseo_focuskw",
        value: "Maquillaje y peinado social a domicilio",
      },
      {
        id: 110355,
        key: "_yoast_wpseo_metadesc",
        value:
          "El maquillaje social en Bogot\u00e1, pretende destacar tu belleza y tus facciones de acuerdo al evento al que vayas y al look que vas a usar.",
      },
      { id: 110356, key: "_yoast_wpseo_linkdex", value: "38" },
      { id: 110357, key: "pi_dcw_product_redirect", value: "0" },
      { id: 110358, key: "pi_dcw_product_overwrite_global", value: "0" },
      { id: 110359, key: "pi_dcw_product_redirect_to_page", value: "" },
      { id: 110360, key: "new_tab", value: "1" },
      { id: 110361, key: "_catcbll_btn_label", value: [""] },
      { id: 110362, key: "_catcbll_btn_link", value: [""] },
      { id: 110363, key: "mwb_product_points_enable", value: "no" },
      { id: 110364, key: "mwb_points_product_value", value: "" },
      { id: 110365, key: "_last_editor_used_jetpack", value: "classic-editor" },
      { id: 110366, key: "rank_math_analytic_object_id", value: "2791" },
      { id: 110367, key: "rank_math_internal_links_processed", value: "1" },
      { id: 110368, key: "rank_math_seo_score", value: "86" },
      {
        id: 110369,
        key: "rank_math_focus_keyword",
        value: "maquillaje y peinado",
      },
      { id: 110370, key: "_rank_math_gtin_code", value: "" },
      { id: 110371, key: "rank_math_primary_product_cat", value: "0" },
      {
        id: 110372,
        key: "links_for_sold",
        value:
          '"https://api.whatsapp.com/send/?phone=573147428757&text&type=phone_number&app_absent=0"',
      },
    ],
    stock_status: "instock",
    has_options: false,
    _links: {
      self: [{ href: "https://calyaan.com/wp-json/wc/v3/products/12316" }],
      collection: [{ href: "https://calyaan.com/wp-json/wc/v3/products" }],
    },
  },
  {
    id: 12309,
    name: "Limpieza espalda profunda a domicilio",
    slug: "limpieza-espalda-profunda",
    permalink: "https://calyaan.com/producto/limpieza-espalda-profunda/",
    date_created: "2023-05-10T22:35:13",
    date_created_gmt: "2023-05-11T03:35:13",
    date_modified: "2023-05-10T22:42:38",
    date_modified_gmt: "2023-05-11T03:42:38",
    type: "simple",
    status: "publish",
    featured: false,
    catalog_visibility: "visible",
    description:
      "<p>*La limpieza espalda profunda a domicilio* es un procedimiento de mantenimiento que elimina todas las impurezas que se encuentran en la piel generadas por el mismo cuerpo y por el ambiente, estas impurezas son el origen de imperfecciones, acn\u00e9, arrugas prematuras y p\u00e9rdida de brillo.</p>\n<p>Una limpieza espalda profunda recupera la luminosidad y uniformidad de tu cara. Aprende sobre c\u00f3mo la limpieza espalda evita imperfecciones por acn\u00e9 y arrugas y sobre los diferentes tratamientos de limpieza de espalda que puedes hacer en casa.</p>\n<h2><strong>Hazte regularmente una limpieza espalda para que la grasa, la contaminaci\u00f3n no te roben los a\u00f1os</strong></h2>\n<p>&nbsp;</p>\n<p>La suciedad, la contaminaci\u00f3n ambiental, la grasa, el maquillaje, el clima e incluso el estr\u00e9s son algunos factores que hacen que la piel\u00a0<strong>pierda higiene</strong>\u00a0y con ella toda\u00a0<strong>vitalidad y luminosidad.</strong></p>\n<p>&nbsp;</p>\n<p><strong>Lucir radiante</strong> con una espalda <strong>uniforme</strong>\u00a0y\u00a0<strong>luminosa</strong>\u00a0es importante para esas fotos especiales y citas importantes donde quieres destacarte y llamar la atenci\u00f3n.</p>\n",
    short_description:
      "<p>*La limpieza espalda profunda a domicilio* es un procedimiento de mantenimiento que elimina todas las impurezas que se encuentran en la piel generadas por el mismo cuerpo y por el ambiente, estas impurezas son el origen de imperfecciones, acn\u00e9, arrugas prematuras y p\u00e9rdida de brillo.</p>\n",
    sku: "",
    price: "270000",
    regular_price: "395000",
    sale_price: "270000",
    date_on_sale_from: null,
    date_on_sale_from_gmt: null,
    date_on_sale_to: null,
    date_on_sale_to_gmt: null,
    on_sale: true,
    purchasable: true,
    total_sales: 0,
    virtual: false,
    downloadable: false,
    downloads: [],
    download_limit: -1,
    download_expiry: -1,
    external_url: "",
    button_text: "",
    tax_status: "taxable",
    tax_class: "",
    manage_stock: false,
    stock_quantity: null,
    backorders: "no",
    backorders_allowed: false,
    backordered: false,
    low_stock_amount: null,
    sold_individually: false,
    weight: "",
    dimensions: { length: "", width: "", height: "" },
    shipping_required: true,
    shipping_taxable: true,
    shipping_class: "",
    shipping_class_id: 0,
    reviews_allowed: true,
    average_rating: "0.00",
    rating_count: 0,
    upsell_ids: [],
    cross_sell_ids: [],
    parent_id: 0,
    purchase_note: "",
    categories: [
      { id: 31, name: "Centro de belleza", slug: "centro-belleza-bogota" },
      {
        id: 84,
        name: "Masaje relajante en bogota a domicilio",
        slug: "masaje-relajante-bogota-domicilio",
      },
      { id: 100, name: "Spa en bogota", slug: "spa-en-bogota" },
    ],
    tags: [],
    images: [
      {
        id: 9303,
        date_created: "2022-09-16T05:15:00",
        date_created_gmt: "2022-09-16T15:15:00",
        date_modified: "2022-09-16T05:18:18",
        date_modified_gmt: "2022-09-16T15:18:18",
        src: "https://calyaan.com/wp-content/uploads/2022/09/11-300x300-1.png",
        name: "11-300&#215;300",
        alt: "Limpieza facial profunda",
      },
    ],
    attributes: [],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 9,
    price_html:
      '<del aria-hidden="true"><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>395.000</bdi></span></del> <ins><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>270.000</bdi></span></ins>',
    related_ids: [828, 857, 834, 845, 795],
    meta_data: [
      { id: 110192, key: "rank_math_internal_links_processed", value: "1" },
      { id: 110212, key: "_wa_order_phone_number", value: "numero de calyaan" },
      { id: 110213, key: "_wa_order_button_text", value: "" },
      { id: 110214, key: "_wa_order_custom_message", value: "" },
      { id: 110215, key: "_hide_wa_button", value: "no" },
      { id: 110216, key: "_hide_atc_button", value: "no" },
      { id: 110217, key: "_force_show_atc_button", value: "no" },
      { id: 110218, key: "_product_meta_id", value: "0" },
      { id: 110219, key: "_wc_facebook_sync_enabled", value: "yes" },
      { id: 110220, key: "fb_visibility", value: "yes" },
      { id: 110221, key: "fb_product_description", value: "" },
      {
        id: 110222,
        key: "_wc_facebook_product_image_source",
        value: "product",
      },
      { id: 110223, key: "_wc_facebook_commerce_enabled", value: "no" },
      { id: 110224, key: "fb_product_group_id", value: "6102064246535365" },
      { id: 110225, key: "fb_product_item_id", value: "6102064283202028" },
      { id: 110226, key: "site-sidebar-layout", value: "default" },
      { id: 110227, key: "site-content-layout", value: "default" },
      { id: 110228, key: "theme-transparent-header-meta", value: "default" },
      { id: 110229, key: "stick-header-meta", value: "default" },
      { id: 110230, key: "_yoast_wpseo_primary_product_cat", value: "31" },
      { id: 110231, key: "_yoast_wpseo_content_score", value: "90" },
      {
        id: 110232,
        key: "_yoast_wpseo_estimated-reading-time-minutes",
        value: "1",
      },
      { id: 110233, key: "pi_dcw_product_redirect", value: "0" },
      { id: 110234, key: "pi_dcw_product_overwrite_global", value: "0" },
      { id: 110235, key: "pi_dcw_product_redirect_to_page", value: "" },
      { id: 110236, key: "new_tab", value: "1" },
      { id: 110237, key: "_catcbll_btn_label", value: [""] },
      { id: 110238, key: "_catcbll_btn_link", value: [""] },
      {
        id: 110239,
        key: "_yoast_wpseo_focuskw",
        value: "Limpieza facial profunda",
      },
      {
        id: 110240,
        key: "_yoast_wpseo_metadesc",
        value:
          "La limpieza facial profunda. Es un procedimiento de mantenimiento que elimina todas las impurezas que se encuentran en la piel.",
      },
      { id: 110241, key: "_yoast_wpseo_linkdex", value: "53" },
      { id: 110242, key: "mwb_product_points_enable", value: "no" },
      { id: 110243, key: "mwb_points_product_value", value: "" },
      { id: 110244, key: "_last_editor_used_jetpack", value: "classic-editor" },
      { id: 110245, key: "_yoast_wpseo_wordproof_timestamp", value: "" },
      { id: 110246, key: "rank_math_analytic_object_id", value: "2788" },
      { id: 110247, key: "rank_math_seo_score", value: "84" },
      {
        id: 110248,
        key: "rank_math_focus_keyword",
        value: "limpieza espalda profunda",
      },
      { id: 110249, key: "_rank_math_gtin_code", value: "" },
      { id: 110250, key: "rank_math_internal_links_processed", value: "1" },
      { id: 110251, key: "rank_math_primary_product_cat", value: "0" },
      {
        id: 110252,
        key: "links_for_sold",
        value:
          '"https://api.whatsapp.com/send/?phone=573147428757&text&type=phone_number&app_absent=0"',
      },
    ],
    stock_status: "instock",
    has_options: false,
    _links: {
      self: [{ href: "https://calyaan.com/wp-json/wc/v3/products/12309" }],
      collection: [{ href: "https://calyaan.com/wp-json/wc/v3/products" }],
    },
  },
  {
    id: 12308,
    name: "Drenaje linf\u00e1tico + Limpieza facial profunda",
    slug: "drenaje-linfatico-limpieza-facial-profunda",
    permalink:
      "https://calyaan.com/producto/drenaje-linfatico-limpieza-facial-profunda/",
    date_created: "2023-05-10T22:29:46",
    date_created_gmt: "2023-05-11T03:29:46",
    date_modified: "2023-05-10T22:32:45",
    date_modified_gmt: "2023-05-11T03:32:45",
    type: "simple",
    status: "publish",
    featured: false,
    catalog_visibility: "visible",
    description:
      "<p>El Drenaje linf\u00e1tico es una t\u00e9cnica de masoterapia que se engloba en los campos de la fisioterapia y la medicina alternativa es un tipo de masaje suave y ligero que se aplica sobre el sistema circulatorio cuyo objetivo es movilizar los l\u00edquidos del organismo para favorecer la eliminaci\u00f3n de las sustancias y obtener mayor alivio.</p>\n<p>&nbsp;</p>\n<p>El<strong>\u00a0drenaje linf\u00e1tico</strong>\u00a0es un masaje que act\u00faa sobre los vasos linf\u00e1ticos con el fin de<strong>\u00a0eliminar el l\u00edquido intersticial y linf\u00e1tico</strong>.</p>\n<p>&nbsp;</p>\n<p>Gracias a su acci\u00f3n antiedematosa y analg\u00e9sica sobre las fibras musculares lisas, el drenaje linf\u00e1tico est\u00e1 especialmente indicado para atenuar el llamado efecto piel de naranja de la celulitis y para tratar edemas postquir\u00fargicos o cicatrices.</p>\n<p>En cuanto al efecto sobre las fibras musculares estriadas, este drenaje se propone a los pacientes por su efecto relajante, especialmente en el caso de m\u00fasculos tensos o hipert\u00f3nicos.</p>\n<p>En general, el drenaje linf\u00e1tico aumenta la respuesta del sistema inmunol\u00f3gico,\u00a0<strong>mejorando as\u00ed la respuesta del sistema de defensa</strong>\u00a0en las zonas tratadas con este masaje.</p>\n<p>&nbsp;</p>\n<p>&nbsp;</p>\n",
    short_description:
      "<p>El Drenaje linf\u00e1tico es una t\u00e9cnica de masoterapia que se engloba en los campos de la fisioterapia y la medicina alternativa es un tipo de masaje suave y ligero que se aplica sobre el sistema circulatorio cuyo objetivo es movilizar los l\u00edquidos del organismo para favorecer la eliminaci\u00f3n de las sustancias y obtener mayor alivio.</p>\n",
    sku: "",
    price: "298000",
    regular_price: "340000",
    sale_price: "298000",
    date_on_sale_from: null,
    date_on_sale_from_gmt: null,
    date_on_sale_to: null,
    date_on_sale_to_gmt: null,
    on_sale: true,
    purchasable: true,
    total_sales: 0,
    virtual: false,
    downloadable: false,
    downloads: [],
    download_limit: -1,
    download_expiry: -1,
    external_url: "",
    button_text: "",
    tax_status: "taxable",
    tax_class: "",
    manage_stock: false,
    stock_quantity: null,
    backorders: "no",
    backorders_allowed: false,
    backordered: false,
    low_stock_amount: null,
    sold_individually: false,
    weight: "",
    dimensions: { length: "", width: "", height: "" },
    shipping_required: true,
    shipping_taxable: true,
    shipping_class: "",
    shipping_class_id: 0,
    reviews_allowed: true,
    average_rating: "0.00",
    rating_count: 0,
    upsell_ids: [],
    cross_sell_ids: [],
    parent_id: 0,
    purchase_note: "",
    categories: [
      { id: 31, name: "Centro de belleza", slug: "centro-belleza-bogota" },
      {
        id: 84,
        name: "Masaje relajante en bogota a domicilio",
        slug: "masaje-relajante-bogota-domicilio",
      },
    ],
    tags: [],
    images: [
      {
        id: 846,
        date_created: "2021-06-06T15:23:40",
        date_created_gmt: "2021-06-06T20:23:40",
        date_modified: "2021-06-10T09:24:07",
        date_modified_gmt: "2021-06-10T14:24:07",
        src: "https://calyaan.com/wp-content/uploads/2021/06/8-min-3.jpg",
        name: "Masaje-linf\u00e1tico",
        alt: "Masaje linf\u00e1tico",
      },
    ],
    attributes: [],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 5,
    price_html:
      '<del aria-hidden="true"><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>340.000</bdi></span></del> <ins><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>298.000</bdi></span></ins>',
    related_ids: [860, 865, 828, 858, 10864],
    meta_data: [
      { id: 110124, key: "rank_math_internal_links_processed", value: "1" },
      { id: 110144, key: "_wa_order_phone_number", value: "numero de calyaan" },
      { id: 110145, key: "_wa_order_button_text", value: "" },
      { id: 110146, key: "_wa_order_custom_message", value: "" },
      { id: 110147, key: "_hide_wa_button", value: "no" },
      { id: 110148, key: "_hide_atc_button", value: "no" },
      { id: 110149, key: "_force_show_atc_button", value: "no" },
      { id: 110150, key: "site-sidebar-layout", value: "default" },
      { id: 110151, key: "site-content-layout", value: "default" },
      { id: 110152, key: "theme-transparent-header-meta", value: "default" },
      { id: 110153, key: "stick-header-meta", value: "default" },
      { id: 110154, key: "_yoast_wpseo_primary_product_cat", value: "31" },
      { id: 110155, key: "_yoast_wpseo_content_score", value: "60" },
      {
        id: 110156,
        key: "_yoast_wpseo_estimated-reading-time-minutes",
        value: "1",
      },
      { id: 110157, key: "pi_dcw_product_redirect", value: "0" },
      { id: 110158, key: "pi_dcw_product_overwrite_global", value: "0" },
      { id: 110159, key: "pi_dcw_product_redirect_to_page", value: "" },
      { id: 110160, key: "_product_meta_id", value: "0" },
      { id: 110161, key: "new_tab", value: "1" },
      { id: 110162, key: "_wc_facebook_sync_enabled", value: "yes" },
      { id: 110163, key: "fb_visibility", value: "yes" },
      { id: 110164, key: "fb_product_description", value: "" },
      {
        id: 110165,
        key: "_wc_facebook_product_image_source",
        value: "product",
      },
      { id: 110166, key: "_wc_facebook_commerce_enabled", value: "no" },
      { id: 110167, key: "fb_product_group_id", value: "4876932412390361" },
      { id: 110168, key: "fb_product_item_id", value: "4876932449057024" },
      { id: 110169, key: "_catcbll_btn_label", value: [""] },
      { id: 110170, key: "_catcbll_btn_link", value: [""] },
      {
        id: 110171,
        key: "_yoast_wpseo_focuskw",
        value: "Masaje linf\u00e1tico",
      },
      {
        id: 110172,
        key: "_yoast_wpseo_metadesc",
        value:
          "El Masaje linf\u00e1tico, es una t\u00e9cnica de masoterapia que se engloba en los campos de la medicina alternativa para mover l\u00edquidos.",
      },
      { id: 110173, key: "_yoast_wpseo_linkdex", value: "47" },
      { id: 110174, key: "mwb_product_points_enable", value: "no" },
      { id: 110175, key: "mwb_points_product_value", value: "" },
      { id: 110176, key: "_yoast_wpseo_wordproof_timestamp", value: "" },
      { id: 110177, key: "rank_math_analytic_object_id", value: "2787" },
      { id: 110178, key: "rank_math_seo_score", value: "89" },
      {
        id: 110179,
        key: "rank_math_focus_keyword",
        value: "drenaje linfatico",
      },
      { id: 110180, key: "_rank_math_gtin_code", value: "" },
      { id: 110181, key: "rank_math_internal_links_processed", value: "1" },
      { id: 110182, key: "rank_math_primary_product_cat", value: "0" },
      {
        id: 110183,
        key: "rank_math_ca_keyword",
        value: { keyword: "masaje linf\u00e1tico", country: "all" },
      },
      {
        id: 110184,
        key: "rank_math_contentai_score",
        value: {
          wordCount: "25.41",
          linkCount: "0",
          headingCount: "0",
          mediaCount: "40",
          keywords: "0",
        },
      },
      {
        id: 110185,
        key: "links_for_sold",
        value:
          '"https://api.whatsapp.com/send/?phone=573147428757&text&type=phone_number&app_absent=0"',
      },
      { id: 110186, key: "rank_math_auto_redirect", value: [66] },
    ],
    stock_status: "instock",
    has_options: false,
    _links: {
      self: [{ href: "https://calyaan.com/wp-json/wc/v3/products/12308" }],
      collection: [{ href: "https://calyaan.com/wp-json/wc/v3/products" }],
    },
  },
  {
    id: 12307,
    name: "Masaje reductor + Limpieza facial profunda",
    slug: "masaje-reductor-limpieza-facial-profunda",
    permalink:
      "https://calyaan.com/producto/masaje-reductor-limpieza-facial-profunda/",
    date_created: "2023-05-10T22:29:20",
    date_created_gmt: "2023-05-11T03:29:20",
    date_modified: "2023-05-10T22:33:29",
    date_modified_gmt: "2023-05-11T03:33:29",
    type: "simple",
    status: "publish",
    featured: false,
    catalog_visibility: "visible",
    description:
      '<h2 dir="auto" data-pm-slice="1 1 []">La gu\u00eda definitiva para reducir sus visitas al terapeuta de masaje reductor y 3 beneficios para usted</h2>\n<p>&nbsp;</p>\n<h3 dir="auto">Introducci\u00f3n: \u00bfPor qu\u00e9 es importante la terapia de masaje reductor y cu\u00e1les son los beneficios?</h3>\n<p>&nbsp;</p>\n<p dir="auto">La terapia de <strong>masaje reductor</strong> es una de las terapias alternativas m\u00e1s populares en el mundo y se usa para tratar una variedad de condiciones c\u00f3mo mejorar la silueta y reducir medidas especificas del cuerpo, tambi\u00e9n ayuda a tonificar el musculo. La terapia de <strong>masaje reductor</strong>, o simplemente "masaje", se puede utilizar para mejorar la circulaci\u00f3n, tambi\u00e9n consiste en la aplicaci\u00f3n de productos y movimientos intensos para amoldar las partes del cuerpo que contienen exceso de grasa y l\u00edquidos, este masaje genera un efecto de moldeado y definici\u00f3n corporal.</p>\n<p dir="auto">Los masajes tambi\u00e9n se utilizan como una forma de medicina alternativa. Este tipo de terapia de masaje generalmente la realiza una cosmet\u00f3loga o mesoterapeuta con licencia. En el masaje reductor se trabajan las zonas con mayor cantidad de grasa del cuerpo, provocando calor con especiales movimientos que ayudan a disolver el tejido adiposo.</p>\n<p dir="auto">La misma profesional puede realizar otro tipo de masajes como el masaje relajante o masaje descontracturante, los beneficios de la terapia de masaje son extensos: puede reducir los niveles de estr\u00e9s, aumentar sus niveles de energ\u00eda, aumentar las defensas de su sistema inmunol\u00f3gico contra las bacterias que causan enfermedades, reducir el dolor cr\u00f3nico y la rigidez en las articulaciones y los m\u00fasculos, mejorar el flujo de sangre al coraz\u00f3n y al cerebro mientras reduce presi\u00f3n arterial.</p>\n<h3 dir="auto">C\u00f3mo reducir sus visitas al terapeuta de masaje reductor en un 50 % o m\u00e1s</h3>\n<p>&nbsp;</p>\n<p dir="auto">Los masajes son una excelente manera de reducir el estr\u00e9s o reducir medidas, pero tambi\u00e9n pueden ser costosos.</p>\n<p dir="auto">Afortunadamente, hay varias formas de obtener masajes gratuitos o reducir la cantidad de visitas que debe realizar al masajista.</p>\n<p dir="auto">Hay muchas maneras de reducir sus visitas al masajista en un 50 % o m\u00e1s. Por ejemplo, podr\u00eda usar un rodillo de espuma antes y despu\u00e9s de su entrenamiento en lugar de recibir un masaje de cuerpo completo. Tambi\u00e9n puedes probar algunas t\u00e9cnicas de automasaje como acupresi\u00f3n o reflexolog\u00eda que no requieren ning\u00fan equipo y que no cuestan nada.</p>\n<h3 dir="auto">3 maneras de reducir sus visitas al terapeuta de masaje reductor ahora</h3>\n<p>&nbsp;</p>\n<p dir="auto">Si eres de los que visita a un masajista con frecuencia, sabr\u00e1s que puede ser un h\u00e1bito bastante costoso. Afortunadamente, hay algunas cosas que puede hacer para reducir sus visitas al terapeuta de masaje reductor ahora.</p>\n<p dir="auto">La primera forma es conseguir un sill\u00f3n de masaje para su hogar. Esto le permitir\u00e1 obtener los mismos beneficios que si estuviera recibiendo un masaje profesional en la comodidad de su hogar. La segunda forma es cuidarse m\u00e1s haciendo ejercicio y estir\u00e1ndose regularmente para que sus m\u00fasculos no se tensen y causen dolor. La tercera forma es usar aceites esenciales en usted mismo o en otros con fines terap\u00e9uticos.</p>\n<h3 dir="auto">Conclusi\u00f3n: por qu\u00e9 dej\u00e9 de ir al masajista y comenc\u00e9 a hacer mis propios auto masaje reductor</h3>\n<p dir="auto">He estado yendo a un masajista desde que era un ni\u00f1a. Fue mi madre quien primero me llev\u00f3 a uno y el h\u00e1bito se qued\u00f3 conmigo. Iba todas las semanas, a veces m\u00e1s a menudo si ten\u00eda ganas. Pero luego, un d\u00eda, cuando estaba en la universidad, mi mam\u00e1 me dijo que hab\u00eda dejado de ir donde la cosmet\u00f3loga y comenz\u00f3 a hacerse sus propios masajes reductores.</p>\n<p dir="auto">Pens\u00e9 que estaba loca, pero luego not\u00e9 que hab\u00eda perdido peso y se ve\u00eda m\u00e1s saludable que nunca.</p>\n<p><strong>El masaje reductor</strong> consiste en la aplicaci\u00f3n de productos y movimientos intensos para amoldar las partes del cuerpo que contienen exceso de grasa y l\u00edquidos, este masaje genera un efecto de moldeado y definici\u00f3n corporal.</p>\n<p>En el <strong>masaje reductor</strong> se trabajan las zonas con mayor cantidad de grasa del cuerpo, provocando calor con especiales movimientos que ayudan a disolver el tejido adiposo. Los movimientos y t\u00e9cnicas del masaje reductivo ayudan al intensificar la circulaci\u00f3n y el metabolismo local.</p>\n<p><span style="font-weight: 400;">1-1 PRIMER D\u00cdA\u00a0</span></p>\n<p><span style="font-weight: 400;">*\u00a0 Llenar ficha t\u00e9cnica y foto\u00a0</span></p>\n<p><span style="font-weight: 400;">* An\u00e1lisis nutricional y desintoxicar\u00a0</span></p>\n<p><span style="font-weight: 400;">* Toma de medidas y peso\u00a0</span></p>\n<p><span style="font-weight: 400;">* An\u00e1lisis de piel para saber que productos voy alistar\u00a0</span></p>\n<p><span style="font-weight: 400;">1-2 Exfoliaci\u00f3n\u00a0</span></p>\n<p><span style="font-weight: 400;">* para remover c\u00e9lulas muertas, nos prepara el tejido para que la piel tenga mejor absorci\u00f3n de todo principio activo.</span></p>\n<p><span style="font-weight: 400;">* Retiramos exfoliante en seco\u00a0</span></p>\n<p><span style="font-weight: 400;">1-3 Procedemos hacer masaje reductor\u00a0\u00a0</span></p>\n<p><span style="font-weight: 400;">* Apertura de ganglios\u00a0</span></p>\n<p><span style="font-weight: 400;">* Cada profesional tiene sus t\u00e9cnicas de masaje\u00a0</span></p>\n<p><span style="font-weight: 400;">1-4 Metaloterapia O Madero terap\u00eda\u00a0</span></p>\n<p><span style="font-weight: 400;">* Rodillo, copa y entre otros\u00a0</span></p>\n<p><span style="font-weight: 400;">* Copa \u2013 con esta llevamos a ganglios linf\u00e1ticos y moldeamos\u00a0</span></p>\n<p><span style="font-weight: 400;">1-5 Tonificar para evitar la flacidez\u00a0</span></p>\n<p><span style="font-weight: 400;">2 SEGUNDO D\u00cdA\u00a0</span></p>\n<p><span style="font-weight: 400;">2-1 Apertura de ganglios linf\u00e1ticos\u00a0</span></p>\n<p><span style="font-weight: 400;">2-2 Ultrasonido corporal\u00a0</span></p>\n<p><span style="font-weight: 400;">2-3 Masaje reductor (cada profesional tiene sus t\u00e9cnicas)\u00a0</span></p>\n<p><span style="font-weight: 400;">2-4 Drenaje linf\u00e1ticos\u00a0</span></p>\n<p>&nbsp;</p>\n<p><span style="font-weight: 400;">3 TERCER D\u00cdA\u00a0</span></p>\n<p><span style="font-weight: 400;">3-1 Apertura de ganglios linf\u00e1ticos\u00a0</span></p>\n<p><span style="font-weight: 400;">3-2 Faja t\u00e9rmica con gel caliente y osm\u00f3tico\u00a0 \u00a0 ( por 20 minutos )\u00a0</span></p>\n<p><span style="font-weight: 400;">3- 3 Masaje reductor\u00a0</span></p>\n<p><span style="font-weight: 400;">3-4 tonificar\u00a0</span></p>\n<p>&nbsp;</p>\n<p><span style="font-weight: 400;">4 CUARTO D\u00cdA</span></p>\n<p><span style="font-weight: 400;">* Avisar a la empresa que estamos en la cuarta d\u00eda para el siguiente abono\u00a0</span></p>\n<p><span style="font-weight: 400;">4-1 Apertura de ganglios linf\u00e1ticos\u00a0</span></p>\n<p><span style="font-weight: 400;">4-2 Cavitaci\u00f3n\u00a0</span></p>\n<p><span style="font-weight: 400;">4-3 Masaje reductor\u00a0</span></p>\n<p><span style="font-weight: 400;">4-5 Drenaje linf\u00e1tico\u00a0</span></p>\n<p><span style="font-weight: 400;">5 QUINTO D\u00cdA\u00a0</span></p>\n<p><span style="font-weight: 400;">5-1 Toma de medidas \u00a0 para ver cambios\u00a0</span></p>\n<p><span style="font-weight: 400;">5-2 Apertura de ganglios linf\u00e1ticos\u00a0</span></p>\n<p><span style="font-weight: 400;">5-3 Masaje reductor\u00a0</span></p>\n<p><span style="font-weight: 400;">5-4 Metaloterapia o Madero terap\u00eda</span></p>\n<p><span style="font-weight: 400;">5-1 Tonificar</span></p>\n<p>&nbsp;</p>\n<p><span style="font-weight: 400;">6 SEXTO D\u00cdA\u00a0</span></p>\n<p><span style="font-weight: 400;">6-1 Apertura de ganglios linf\u00e1ticos\u00a0</span></p>\n<p><span style="font-weight: 400;">6-2 Manta t\u00e9rmica con gel y osm\u00f3tico\u00a0</span></p>\n<p><span style="font-weight: 400;">6-3 Masaje reductor\u00a0</span></p>\n<p><span style="font-weight: 400;">6-4 Radio frecuencia corporal\u00a0</span></p>\n<p>&nbsp;</p>\n<p><span style="font-weight: 400;">7 SEPTIMO D\u00cdA\u00a0</span></p>\n<p><span style="font-weight: 400;">7-1 Apertura de ganglios linf\u00e1ticos\u00a0</span></p>\n<p><span style="font-weight: 400;">7-2 Ultrasonido corporal\u00a0</span></p>\n<p><span style="font-weight: 400;">7-3 Masaje reductor\u00a0</span></p>\n<p><span style="font-weight: 400;">7-4 Drenaje linf\u00e1tico\u00a0</span></p>\n<p><span style="font-weight: 400;">8 OCTAVO D\u00cdA</span></p>\n<p><span style="font-weight: 400;">8-1 Apertura de ganglios linf\u00e1ticos\u00a0</span></p>\n<p><span style="font-weight: 400;">8-2 Masaje reductor\u00a0</span></p>\n<p><span style="font-weight: 400;">8-3 Metaloterapia o Madero terap\u00eda</span></p>\n<p><span style="font-weight: 400;">8-4 Gimnasia pasiva\u00a0</span></p>\n<p>&nbsp;</p>\n<p><span style="font-weight: 400;">9 NOVENO D\u00cdA</span></p>\n<p><span style="font-weight: 400;">9-1 Apertura de ganglios linf\u00e1ticos\u00a0</span></p>\n<p><span style="font-weight: 400;">9-2 Manta t\u00e9rmica gel y osm\u00f3tico\u00a0</span></p>\n<p><span style="font-weight: 400;">9-3Masaje reductor</span></p>\n<p><span style="font-weight: 400;">9-4 Radiofrecuencia\u00a0</span></p>\n<p>&nbsp;</p>\n<p><span style="font-weight: 400;">10 DECIMO D\u00cdA: Toma de medidas y fotos\u00a0</span></p>\n<p><span style="font-weight: 400;">10-1 Apertura de ganglios\u00a0</span></p>\n<p><span style="font-weight: 400;">10-2 Drenaje linf\u00e1ticos\u00a0</span></p>\n<p><span style="font-weight: 400;">10-3 Gimnasia pasiva\u00a0</span></p>\n<p><span style="font-weight: 400;">10-4 tonificar\u00a0</span></p>\n<p>&nbsp;</p>\n',
    short_description:
      "<p>El masaje reductor, <strong>es sin camilla:</strong> consiste en la aplicaci\u00f3n de productos y movimientos intensos para moldear las partes del cuerpo que contienen exceso de grasa y l\u00edquidos, este masaje genera un efecto de moldeado, reduce la silueta y tonifica la zona.</p>\n",
    sku: "",
    price: "298000",
    regular_price: "350000",
    sale_price: "298000",
    date_on_sale_from: null,
    date_on_sale_from_gmt: null,
    date_on_sale_to: null,
    date_on_sale_to_gmt: null,
    on_sale: true,
    purchasable: true,
    total_sales: 0,
    virtual: false,
    downloadable: false,
    downloads: [],
    download_limit: -1,
    download_expiry: -1,
    external_url: "",
    button_text: "",
    tax_status: "taxable",
    tax_class: "",
    manage_stock: false,
    stock_quantity: null,
    backorders: "no",
    backorders_allowed: false,
    backordered: false,
    low_stock_amount: null,
    sold_individually: false,
    weight: "",
    dimensions: { length: "", width: "", height: "" },
    shipping_required: true,
    shipping_taxable: true,
    shipping_class: "",
    shipping_class_id: 0,
    reviews_allowed: true,
    average_rating: "0.00",
    rating_count: 0,
    upsell_ids: [],
    cross_sell_ids: [],
    parent_id: 0,
    purchase_note: "",
    categories: [
      { id: 31, name: "Centro de belleza", slug: "centro-belleza-bogota" },
      {
        id: 84,
        name: "Masaje relajante en bogota a domicilio",
        slug: "masaje-relajante-bogota-domicilio",
      },
    ],
    tags: [],
    images: [
      {
        id: 8981,
        date_created: "2022-06-20T15:09:18",
        date_created_gmt: "2022-06-21T01:09:18",
        date_modified: "2023-06-01T06:09:00",
        date_modified_gmt: "2023-06-01T16:09:00",
        src: "https://calyaan.com/wp-content/uploads/2022/06/como_funciona_el_masaje_reductivo_24646_paso_1_600.jpg",
        name: "masajes reductores de abdomen y cintura",
        alt: "masajes reductores de abdomen y cintura",
      },
    ],
    attributes: [],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 67,
    price_html:
      '<del aria-hidden="true"><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>350.000</bdi></span></del> <ins><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>298.000</bdi></span></ins>',
    related_ids: [828, 843, 801, 864, 834],
    meta_data: [
      { id: 110060, key: "rank_math_internal_links_processed", value: "1" },
      { id: 110080, key: "_wa_order_phone_number", value: "numero de calyaan" },
      { id: 110081, key: "_wa_order_button_text", value: "" },
      { id: 110082, key: "_wa_order_custom_message", value: "" },
      { id: 110083, key: "_hide_wa_button", value: "no" },
      { id: 110084, key: "_hide_atc_button", value: "no" },
      { id: 110085, key: "_force_show_atc_button", value: "no" },
      { id: 110086, key: "site-sidebar-layout", value: "default" },
      { id: 110087, key: "site-content-layout", value: "default" },
      { id: 110088, key: "theme-transparent-header-meta", value: "default" },
      { id: 110089, key: "stick-header-meta", value: "default" },
      { id: 110090, key: "_yoast_wpseo_primary_product_cat", value: "31" },
      {
        id: 110091,
        key: "_yoast_wpseo_estimated-reading-time-minutes",
        value: "1",
      },
      { id: 110092, key: "_yoast_wpseo_content_score", value: "90" },
      { id: 110093, key: "pi_dcw_product_redirect", value: "0" },
      { id: 110094, key: "pi_dcw_product_overwrite_global", value: "0" },
      { id: 110095, key: "pi_dcw_product_redirect_to_page", value: "" },
      { id: 110096, key: "_product_meta_id", value: "0" },
      { id: 110097, key: "new_tab", value: "1" },
      { id: 110098, key: "_wc_facebook_sync_enabled", value: "yes" },
      { id: 110099, key: "fb_visibility", value: "yes" },
      { id: 110100, key: "fb_product_description", value: "" },
      {
        id: 110101,
        key: "_wc_facebook_product_image_source",
        value: "product",
      },
      { id: 110102, key: "_wc_facebook_commerce_enabled", value: "no" },
      { id: 110103, key: "fb_product_group_id", value: "4371996986239543" },
      { id: 110104, key: "fb_product_item_id", value: "4371997032906205" },
      { id: 110105, key: "_catcbll_btn_label", value: [""] },
      { id: 110106, key: "_catcbll_btn_link", value: [""] },
      {
        id: 110107,
        key: "_yoast_wpseo_focuskw",
        value: "Masaje reductor bogota a domicilio",
      },
      {
        id: 110108,
        key: "_yoast_wpseo_metadesc",
        value:
          "El masaje reductor consiste en la aplicaci\u00f3n de productos y movimientos intensos con un efecto de moldeado y definici\u00f3n corporal.",
      },
      { id: 110109, key: "_yoast_wpseo_linkdex", value: "40" },
      { id: 110110, key: "mwb_product_points_enable", value: "no" },
      { id: 110111, key: "mwb_points_product_value", value: "" },
      { id: 110112, key: "_last_editor_used_jetpack", value: "classic-editor" },
      { id: 110113, key: "_yoast_wpseo_wordproof_timestamp", value: "" },
      { id: 110114, key: "rank_math_analytic_object_id", value: "2786" },
      { id: 110115, key: "rank_math_seo_score", value: "89" },
      { id: 110116, key: "rank_math_focus_keyword", value: "masaje reductor" },
      { id: 110117, key: "_rank_math_gtin_code", value: "" },
      { id: 110118, key: "rank_math_internal_links_processed", value: "1" },
      { id: 110119, key: "rank_math_primary_product_cat", value: "0" },
      {
        id: 110120,
        key: "rank_math_ca_keyword",
        value: { keyword: "masaje reductor", country: "es_CO" },
      },
      {
        id: 110121,
        key: "rank_math_contentai_score",
        value: {
          wordCount: "100",
          linkCount: "0",
          headingCount: "100",
          mediaCount: "40",
          keywords: "18.18",
        },
      },
      {
        id: 110122,
        key: "links_for_sold",
        value:
          '"https://api.whatsapp.com/send/?phone=573147428757&text&type=phone_number&app_absent=0"',
      },
    ],
    stock_status: "instock",
    has_options: false,
    _links: {
      self: [{ href: "https://calyaan.com/wp-json/wc/v3/products/12307" }],
      collection: [{ href: "https://calyaan.com/wp-json/wc/v3/products" }],
    },
  },
  {
    id: 12306,
    name: "Reflexolog\u00eda podal + Limpieza facial profunda",
    slug: "reflexologia-podal-limpieza-facial-profunda",
    permalink:
      "https://calyaan.com/producto/reflexologia-podal-limpieza-facial-profunda/",
    date_created: "2023-05-10T22:27:55",
    date_created_gmt: "2023-05-11T03:27:55",
    date_modified: "2023-05-10T22:33:21",
    date_modified_gmt: "2023-05-11T03:33:21",
    type: "simple",
    status: "publish",
    featured: false,
    catalog_visibility: "visible",
    description:
      "<h1></h1>\n<h1>3 formas de aliviar el estr\u00e9s: Reflexolog\u00eda podal, masaje y aromaterapia.</h1>\n<p>&nbsp;</p>\n<p>La reflexolog\u00eda podal es la terapia que genera presi\u00f3n en los pies o manos con el fin de aliviar dolores y molestias.</p>\n<p>&nbsp;</p>\n<p>La reflexolog\u00eda podal es generalmente una terapia relajante que tambi\u00e9n ayuda a disminuir el estr\u00e9s.</p>\n<p>&nbsp;</p>\n<p>Los reflex\u00f3logos usan tablas de pies para guiarlos a medida que aplican presi\u00f3n en \u00e1reas espec\u00edficas.</p>\n<p>&nbsp;</p>\n<p>La reflexolog\u00eda podal a veces se combina con otras terapias pr\u00e1cticas y la pueden ofrecer quiropr\u00e1cticos y fisioterapeutas, entre otros.</p>\n<p>&nbsp;</p>\n<p>Varios estudios indican que la reflexolog\u00eda podal puede reducir el dolor y los s\u00edntomas psicol\u00f3gicos, como el estr\u00e9s y la ansiedad, y aumentar la relajaci\u00f3n y el sue\u00f1o.</p>\n<p>&nbsp;</p>\n<p>Dado que la reflexolog\u00eda podal tambi\u00e9n es de bajo riesgo, puede ser una opci\u00f3n razonable si buscas relajaci\u00f3n y alivio del estr\u00e9s.</p>\n<p>&nbsp;</p>\n<p>&nbsp;</p>\n",
    short_description:
      "<p>La reflexolog\u00eda podal es la terapia que genera presi\u00f3n en los pies o manos con el fin de aliviar dolores y molestias. La reflexolog\u00eda podal es generalmente una terapia relajante que tambi\u00e9n ayuda a disminuir el estr\u00e9s de todo el cuerpo</p>\n",
    sku: "",
    price: "278000",
    regular_price: "350000",
    sale_price: "278000",
    date_on_sale_from: null,
    date_on_sale_from_gmt: null,
    date_on_sale_to: null,
    date_on_sale_to_gmt: null,
    on_sale: true,
    purchasable: true,
    total_sales: 0,
    virtual: false,
    downloadable: false,
    downloads: [],
    download_limit: -1,
    download_expiry: -1,
    external_url: "",
    button_text: "",
    tax_status: "taxable",
    tax_class: "",
    manage_stock: false,
    stock_quantity: null,
    backorders: "no",
    backorders_allowed: false,
    backordered: false,
    low_stock_amount: null,
    sold_individually: false,
    weight: "",
    dimensions: { length: "", width: "", height: "" },
    shipping_required: true,
    shipping_taxable: true,
    shipping_class: "",
    shipping_class_id: 0,
    reviews_allowed: true,
    average_rating: "0.00",
    rating_count: 0,
    upsell_ids: [],
    cross_sell_ids: [],
    parent_id: 0,
    purchase_note: "",
    categories: [
      { id: 31, name: "Centro de belleza", slug: "centro-belleza-bogota" },
      {
        id: 84,
        name: "Masaje relajante en bogota a domicilio",
        slug: "masaje-relajante-bogota-domicilio",
      },
    ],
    tags: [],
    images: [
      {
        id: 5997,
        date_created: "2022-04-05T03:47:19",
        date_created_gmt: "2022-04-05T13:47:19",
        date_modified: "2022-09-16T04:38:40",
        date_modified_gmt: "2022-09-16T14:38:40",
        src: "https://calyaan.com/wp-content/uploads/2022/03/8AC3807-scaled.jpg",
        name: "_8AC3807",
        alt: "Reflexolog\u00eda",
      },
      {
        id: 5997,
        date_created: "2022-04-05T03:47:19",
        date_created_gmt: "2022-04-05T13:47:19",
        date_modified: "2022-09-16T04:38:40",
        date_modified_gmt: "2022-09-16T14:38:40",
        src: "https://calyaan.com/wp-content/uploads/2022/03/8AC3807-scaled.jpg",
        name: "_8AC3807",
        alt: "Reflexolog\u00eda",
      },
    ],
    attributes: [],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 81,
    price_html:
      '<del aria-hidden="true"><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>350.000</bdi></span></del> <ins><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>278.000</bdi></span></ins>',
    related_ids: [857, 816, 847, 826, 795],
    meta_data: [
      { id: 110007, key: "rank_math_internal_links_processed", value: "1" },
      { id: 110028, key: "pi_dcw_product_redirect", value: "0" },
      { id: 110029, key: "pi_dcw_product_overwrite_global", value: "0" },
      { id: 110030, key: "pi_dcw_product_redirect_to_page", value: "" },
      { id: 110031, key: "_product_meta_id", value: "0" },
      { id: 110032, key: "new_tab", value: "1" },
      { id: 110033, key: "_wc_facebook_sync_enabled", value: "yes" },
      { id: 110034, key: "fb_visibility", value: "yes" },
      { id: 110035, key: "fb_product_description", value: "" },
      {
        id: 110036,
        key: "_wc_facebook_product_image_source",
        value: "product",
      },
      { id: 110037, key: "_wc_facebook_commerce_enabled", value: "no" },
      { id: 110038, key: "site-sidebar-layout", value: "default" },
      { id: 110039, key: "site-content-layout", value: "default" },
      { id: 110040, key: "theme-transparent-header-meta", value: "default" },
      { id: 110041, key: "stick-header-meta", value: "default" },
      {
        id: 110042,
        key: "_yoast_wpseo_estimated-reading-time-minutes",
        value: "",
      },
      { id: 110043, key: "mwb_product_points_enable", value: "no" },
      { id: 110044, key: "mwb_points_product_value", value: "" },
      { id: 110045, key: "_last_editor_used_jetpack", value: "classic-editor" },
      { id: 110046, key: "_yoast_wpseo_primary_product_cat", value: "81" },
      { id: 110047, key: "_yoast_wpseo_wordproof_timestamp", value: "" },
      {
        id: 110048,
        key: "_yoast_wpseo_metadesc",
        value:
          'Alivia el estr\u00e9s por medio de la terapia "Reflexolog\u00eda", ejerciendo presi\u00f3n en partes especificas del cuerpo',
      },
      { id: 110049, key: "rank_math_analytic_object_id", value: "2785" },
      { id: 110050, key: "rank_math_seo_score", value: "75" },
      {
        id: 110051,
        key: "rank_math_focus_keyword",
        value: "reflexologia podal",
      },
      { id: 110052, key: "_rank_math_gtin_code", value: "" },
      { id: 110053, key: "rank_math_internal_links_processed", value: "1" },
      { id: 110054, key: "rank_math_primary_product_cat", value: "0" },
      {
        id: 110055,
        key: "links_for_sold",
        value:
          '"https://api.whatsapp.com/send/?phone=573147428757&text&type=phone_number&app_absent=0"',
      },
    ],
    stock_status: "instock",
    has_options: false,
    _links: {
      self: [{ href: "https://calyaan.com/wp-json/wc/v3/products/12306" }],
      collection: [{ href: "https://calyaan.com/wp-json/wc/v3/products" }],
    },
  },
  {
    id: 12305,
    name: "Masaje t\u00e1ntrico + Limpieza facial profunda",
    slug: "masaje-tantrico-limpieza-facial-profunda",
    permalink:
      "https://calyaan.com/producto/masaje-tantrico-limpieza-facial-profunda/",
    date_created: "2023-05-10T22:27:48",
    date_created_gmt: "2023-05-11T03:27:48",
    date_modified: "2023-05-10T22:33:12",
    date_modified_gmt: "2023-05-11T03:33:12",
    type: "simple",
    status: "publish",
    featured: false,
    catalog_visibility: "visible",
    description:
      '<h1></h1>\n<h1>Masaje t\u00e1ntrico</h1>\n<p>&nbsp;</p>\n<p>Para saber qu\u00e9 es un Masaje t\u00e1ntrico para hombre , primero debemos conocer qu\u00e9 es el tantra o masaje t\u00e1ntrico. El tantra o masaje t\u00e1ntrico es un t\u00e9rmino muy interesante que procede de la filosof\u00eda oriental. Este concepto se refiere al desarrollo espiritual de un individuo. Dicho de otra forma, el masaje especial o masaje t\u00e1ntrico tienen como objetivo, la \u00faltima la liberaci\u00f3n del esp\u00edritu y su expansi\u00f3n.</p>\n<p>El objetivo de este masaje t\u00e1ntrico es la generaci\u00f3n y manejo de una energ\u00eda capaz de llevar a un estado de consciencia y plenitud a la persona.</p>\n<p>Los beneficios de este masaje est\u00e1n destinados en una excelente t\u00e9cnica para alejar la ansiedad y conocer nuestro propio cuerpo:</p>\n<ul>\n<li>Ayuda a mantener el equilibrio mental y f\u00edsico.</li>\n<li>Disminuye la ansiedad y el estr\u00e9s.</li>\n<li>Este masaje esta orientado a favorecer un estado de calma.</li>\n<li>Tomar conciencia de nuestro cuerpo.</li>\n<li>Proporciona un buen estado de \u00e1nimo.</li>\n<li>Mejora el proceso de respiraci\u00f3n.</li>\n<li>Fomenta la relaci\u00f3n f\u00edsica y afectiva de la pareja.</li>\n</ul>\n<p>&nbsp;</p>\n<h2 dir="auto" data-pm-slice="1 1 []">3 formas de obtener una mejor experiencia de masaje t\u00e1ntrico</h2>\n<p>&nbsp;</p>\n<p dir="auto">En este art\u00edculo, discutir\u00e9 las tres formas de obtener una mejor experiencia de masaje tailand\u00e9s.</p>\n<p dir="auto">- Beneficios del masaje t\u00e1ntrico</p>\n<p dir="auto">- C\u00f3mo obtener una mejor experiencia de masaje tailand\u00e9s</p>\n<p dir="auto">- Consejos para obtener una mejor experiencia de masaje tailand\u00e9s.</p>\n<p dir="auto">- Qu\u00e9 hacer antes de recibir un masaje tailand\u00e9s</p>\n<p dir="auto">- Qu\u00e9 no hacer antes de recibir un masaje tailand\u00e9s</p>\n<h3 dir="auto">Introducci\u00f3n: \u00bfQu\u00e9 es un masaje t\u00e1ntrico?</h3>\n<p>&nbsp;</p>\n<p dir="auto">El masaje tailand\u00e9s es un tipo de masaje que se origin\u00f3 en Tailandia. Se llama \u201cThai\u201d porque se desarroll\u00f3 en la ciudad de Bangkok y comparte similitudes con la Medicina Tradicional China.</p>\n<p dir="auto">El masaje tailand\u00e9s es una forma de trabajo corporal que implica el uso de presi\u00f3n sobre el cuerpo para manipular las v\u00edas de energ\u00eda y aliviar la tensi\u00f3n. Puede ser realizado por un practicante experimentado o por uno mismo en casa.</p>\n<p dir="auto">El tipo de masaje tailand\u00e9s m\u00e1s conocido se llama "masaje tradicional tailand\u00e9s" o "medicina tradicional tailandesa".</p>\n<h3 dir="auto">1. Desarrolle un cronograma para su masaje t\u00e1ntrico</h3>\n<p>&nbsp;</p>\n<p dir="auto">Primero, determine el mejor d\u00eda en que puede programar su cita. Esto generalmente se basa en su horario de trabajo y cualquier otro compromiso que pueda tener.</p>\n<p dir="auto">En segundo lugar, busque el mejor momento para programar su cita. Las sesiones de masaje tailand\u00e9s suelen durar alrededor de una hora. El tipo de sesi\u00f3n que est\u00e9 teniendo determinar\u00e1 la duraci\u00f3n de la sesi\u00f3n, pero la mayor\u00eda de las sesiones de masaje tailand\u00e9s duran alrededor de una hora.</p>\n<p dir="auto">Tercero, encuentre un lugar para su sesi\u00f3n de masaje tailand\u00e9s. Si est\u00e1 buscando un spa en su \u00e1rea, hay muchos lugares que ofrecen este servicio y podr\u00e1n adaptarse a sus necesidades y preferencias con facilidad.</p>\n<p dir="auto">En cuarto lugar, reserve una sesi\u00f3n con un terapeuta que ofrezca masajes tailandeses en persona o en l\u00ednea.</p>\n<h3 dir="auto">2. Encuentra el sal\u00f3n adecuado para tus necesidades y presupuesto</h3>\n<p>&nbsp;</p>\n<p dir="auto">Si est\u00e1 buscando un sal\u00f3n, puede encontrar el adecuado para sus necesidades y presupuesto.</p>\n<p dir="auto">Los salones en Singapur var\u00edan desde salones peque\u00f1os e independientes hasta grandes cadenas internacionales.</p>\n<p dir="auto">Hay muchos factores que debes considerar antes de elegir tu pr\u00f3ximo sal\u00f3n.</p>\n<p dir="auto">\u00bfC\u00f3mo es el ambiente? \u00bfQu\u00e9 servicios ofrecen? \u00bfEs f\u00e1cil reservar una cita? \u00bfCu\u00e1l es su estructura de precios? \u00bfCu\u00e1nto tiempo tendr\u00e9 que esperar entre servicios?</p>\n<h3 dir="auto">3. Elija el terapeuta adecuado para usted</h3>\n<p>&nbsp;</p>\n<p dir="auto">Encontrar el sal\u00f3n adecuado para sus necesidades y presupuesto puede ser una tarea abrumadora. Pero, con todas las opciones disponibles, es posible encontrar el sal\u00f3n perfecto para ti.</p>\n<p dir="auto">El primer paso para encontrar el sal\u00f3n adecuado es obtener un corte de cabello que te guste de un estilista que entienda tu tipo de cabello. Una vez que haya encontrado a este estilista, es importante averiguar si trabaja en un sal\u00f3n o es independiente. Si trabajan en un sal\u00f3n, preg\u00fantales cu\u00e1les son sus salones favoritos en la ciudad y por qu\u00e9 los recomiendan. Si son independientes, preg\u00fantales qu\u00e9 tipo de servicios brindan y cu\u00e1les son sus precios.</p>\n<p dir="auto">Una vez que haya reducido sus opciones en funci\u00f3n de estas preguntas, es hora de visitar cada uno de estos salones y tener una idea de c\u00f3mo funcionan. Esto le dar\u00e1 una idea de cu\u00e1nto tiempo toma cada servicio y qu\u00e9 tipo de experiencia de servicio al cliente puede esperar all\u00ed.</p>\n',
    short_description:
      "<p>Para saber qu\u00e9 es un Masaje Especial, primero debemos conocer qu\u00e9 es el tantra o el masaje t\u00e1ntrico. El tantra o masaje t\u00e1ntrico es un t\u00e9rmino muy interesante que procede de la filosof\u00eda oriental. Este concepto se refiere al desarrollo espiritual de un individuo. Dicho de otra forma, el masaje especial o masaje t\u00e1ntrico tienen como objetivo, la \u00faltima la liberaci\u00f3n del esp\u00edritu y su expansi\u00f3n.</p>\n<p>El objetivo de este masaje t\u00e1ntrico es la generaci\u00f3n y manejo de una energ\u00eda capaz de llevar a un estado de consciencia y plenitud a la persona.</p>\n",
    sku: "",
    price: "448000",
    regular_price: "800000",
    sale_price: "448000",
    date_on_sale_from: null,
    date_on_sale_from_gmt: null,
    date_on_sale_to: null,
    date_on_sale_to_gmt: null,
    on_sale: true,
    purchasable: true,
    total_sales: 0,
    virtual: false,
    downloadable: false,
    downloads: [],
    download_limit: -1,
    download_expiry: -1,
    external_url: "",
    button_text: "",
    tax_status: "taxable",
    tax_class: "",
    manage_stock: false,
    stock_quantity: null,
    backorders: "no",
    backorders_allowed: false,
    backordered: false,
    low_stock_amount: null,
    sold_individually: false,
    weight: "",
    dimensions: { length: "", width: "", height: "" },
    shipping_required: true,
    shipping_taxable: true,
    shipping_class: "",
    shipping_class_id: 0,
    reviews_allowed: true,
    average_rating: "0.00",
    rating_count: 0,
    upsell_ids: [],
    cross_sell_ids: [],
    parent_id: 0,
    purchase_note: "",
    categories: [
      { id: 31, name: "Centro de belleza", slug: "centro-belleza-bogota" },
      {
        id: 84,
        name: "Masaje relajante en bogota a domicilio",
        slug: "masaje-relajante-bogota-domicilio",
      },
    ],
    tags: [],
    images: [
      {
        id: 4740,
        date_created: "2022-01-25T12:28:03",
        date_created_gmt: "2022-01-25T22:28:03",
        date_modified: "2022-09-16T04:02:14",
        date_modified_gmt: "2022-09-16T14:02:14",
        src: "https://calyaan.com/wp-content/uploads/2022/01/pexels-koolshooters-6628611-1-scaled.jpg",
        name: "pexels-koolshooters-6628611 (1)",
        alt: "Masaje especial para hombres",
      },
    ],
    attributes: [],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 70,
    price_html:
      '<del aria-hidden="true"><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>800.000</bdi></span></del> <ins><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>448.000</bdi></span></ins>',
    related_ids: [834, 862, 847, 795, 841],
    meta_data: [
      { id: 109945, key: "rank_math_internal_links_processed", value: "1" },
      { id: 109965, key: "_wa_order_phone_number", value: "numero de calyaan" },
      { id: 109966, key: "_wa_order_button_text", value: "" },
      { id: 109967, key: "_wa_order_custom_message", value: "" },
      { id: 109968, key: "_hide_wa_button", value: "no" },
      { id: 109969, key: "_hide_atc_button", value: "no" },
      { id: 109970, key: "_force_show_atc_button", value: "no" },
      { id: 109971, key: "_product_meta_id", value: "0" },
      { id: 109972, key: "_wc_facebook_sync_enabled", value: "yes" },
      { id: 109973, key: "fb_visibility", value: "no" },
      { id: 109974, key: "fb_product_description", value: "" },
      {
        id: 109975,
        key: "_wc_facebook_product_image_source",
        value: "product",
      },
      { id: 109976, key: "_wc_facebook_commerce_enabled", value: "no" },
      { id: 109977, key: "site-sidebar-layout", value: "default" },
      { id: 109978, key: "site-content-layout", value: "default" },
      { id: 109979, key: "theme-transparent-header-meta", value: "default" },
      { id: 109980, key: "stick-header-meta", value: "default" },
      { id: 109981, key: "_yoast_wpseo_primary_product_cat", value: "31" },
      { id: 109982, key: "_yoast_wpseo_content_score", value: "90" },
      {
        id: 109983,
        key: "_yoast_wpseo_estimated-reading-time-minutes",
        value: "1",
      },
      { id: 109984, key: "pi_dcw_product_redirect", value: "0" },
      { id: 109985, key: "pi_dcw_product_overwrite_global", value: "0" },
      { id: 109986, key: "pi_dcw_product_redirect_to_page", value: "" },
      { id: 109987, key: "new_tab", value: "1" },
      { id: 109988, key: "_catcbll_btn_label", value: [""] },
      { id: 109989, key: "_catcbll_btn_link", value: [""] },
      { id: 109990, key: "_yoast_wpseo_focuskw", value: "Masaje especial" },
      { id: 109991, key: "_yoast_wpseo_linkdex", value: "60" },
      { id: 109992, key: "fb_product_group_id", value: "7168311459860608" },
      { id: 109993, key: "fb_product_item_id", value: "7168311506527270" },
      {
        id: 109994,
        key: "_yoast_wpseo_metadesc",
        value:
          "El objetivo del Masaje Especial o masaje t\u00e1ntrico es la generaci\u00f3n y manejo de una energ\u00eda capaz de llevar a un estado de consciencia.",
      },
      { id: 109995, key: "mwb_product_points_enable", value: "no" },
      { id: 109996, key: "mwb_points_product_value", value: "" },
      { id: 109997, key: "_last_editor_used_jetpack", value: "classic-editor" },
      { id: 109998, key: "_yoast_wpseo_wordproof_timestamp", value: "" },
      { id: 109999, key: "rank_math_analytic_object_id", value: "2784" },
      { id: 110000, key: "rank_math_seo_score", value: "87" },
      { id: 110001, key: "rank_math_focus_keyword", value: "Masaje tantrico" },
      { id: 110002, key: "_rank_math_gtin_code", value: "" },
      { id: 110003, key: "rank_math_internal_links_processed", value: "1" },
      { id: 110004, key: "rank_math_primary_product_cat", value: "0" },
      {
        id: 110005,
        key: "links_for_sold",
        value:
          '"https://api.whatsapp.com/send/?phone=573147428757&text&type=phone_number&app_absent=0"',
      },
    ],
    stock_status: "instock",
    has_options: false,
    _links: {
      self: [{ href: "https://calyaan.com/wp-json/wc/v3/products/12305" }],
      collection: [{ href: "https://calyaan.com/wp-json/wc/v3/products" }],
    },
  },
  {
    id: 12303,
    name: "Masaje relajante + Limpieza facial profunda",
    slug: "masaje-relajante-limpieza-facial-profunda",
    permalink:
      "https://calyaan.com/producto/masaje-relajante-limpieza-facial-profunda/",
    date_created: "2023-05-10T22:15:35",
    date_created_gmt: "2023-05-11T03:15:35",
    date_modified: "2023-05-10T22:24:05",
    date_modified_gmt: "2023-05-11T03:24:05",
    type: "simple",
    status: "publish",
    featured: false,
    catalog_visibility: "visible",
    description:
      '<h1 dir="auto" data-pm-slice="1 1 []"></h1>\n<h1 dir="auto" data-pm-slice="1 1 []">5 beneficios de un masaje relajante que quiz\u00e1s no conozca</h1>\n<p dir="auto">La terapia de masaje es una forma popular de relajaci\u00f3n que puede proporcionar muchos beneficios.</p>\n<p dir="auto">Estos son los 5 principales beneficios de un masaje relajante que quiz\u00e1s no conozcas:</p>\n<p dir="auto">1) La terapia de masaje puede ayudar a aliviar la ansiedad y la depresi\u00f3n</p>\n<p dir="auto">2) Ayuda a reducir el dolor y la rigidez en los m\u00fasculos.</p>\n<p dir="auto">3) Aumenta la circulaci\u00f3n a los tejidos y \u00f3rganos, lo que puede disminuir la presi\u00f3n arterial.</p>\n<p dir="auto">4) La terapia de masaje tambi\u00e9n reduce los niveles de la hormona del estr\u00e9s, lo cual es excelente para la salud de su coraz\u00f3n</p>\n<p dir="auto">5) Se sabe que los masajes aumentan los niveles de serotonina, lo que ayuda a mejorar el estado de \u00e1nimo</p>\n<h3 dir="auto">C\u00f3mo Deshacerse del Estr\u00e9s con el Poder de un Masaje</h3>\n<p>&nbsp;</p>\n<p dir="auto">Un masaje puede ser una forma poderosa de aliviar el estr\u00e9s y la tensi\u00f3n. Puede ayudarte a relajarte y entrar en un estado de relajaci\u00f3n profunda, que es la clave para aliviar el estr\u00e9s.</p>\n<p dir="auto">Hay muchos tipos diferentes de masajes que las personas usan por diferentes razones. Algunas personas optan por un masaje sueco, que se caracteriza por movimientos largos y amasamiento de los m\u00fasculos. Otros pueden preferir un masaje de tejido profundo, que se enfoca en capas m\u00e1s profundas de m\u00fasculos y fascia (un tipo de tejido conectivo).</p>\n<h3 dir="auto">\u00bfQu\u00e9 constituye la mejor experiencia de masaje?</h3>\n<p>&nbsp;</p>\n<p dir="auto">Una gran experiencia de masaje es aquella que se adapta a las necesidades del individuo.</p>\n<p dir="auto">Algunas personas son m\u00e1s sensibles que otras y pueden necesitar un toque m\u00e1s ligero o menos presi\u00f3n. Otros pueden necesitar un trabajo de tejido m\u00e1s profundo dependiendo de su condici\u00f3n. El mejor terapeuta de masaje podr\u00e1 leer el lenguaje corporal del cliente y saber lo que necesita.</p>\n<p dir="auto">Una gran experiencia de masaje es diferente para todos, por lo que es importante averiguar qu\u00e9 constituye una gran experiencia para usted y su tipo de cuerpo antes de programar una cita con un centro de est\u00e9tica espec\u00edfico.</p>\n<h3 dir="auto">5 formas de aumentar tu felicidad recibiendo un masaje relajante</h3>\n<p>&nbsp;</p>\n<p dir="auto">1. Un masaje puede ayudarlo a reducir el estr\u00e9s y la ansiedad, que son los principales contribuyentes a la infelicidad.</p>\n<p dir="auto">2. Recibir un masaje es una buena manera de tomar un descanso de la rutina diaria, lo que puede brindar una oportunidad para la autorreflexi\u00f3n y el crecimiento personal.</p>\n<p dir="auto">3. Un masaje puede ayudarlo a mejorar su estado de \u00e1nimo al liberar endorfinas en el cerebro y tambi\u00e9n aumenta los niveles de serotonina, lo que mejora el estado de \u00e1nimo en general.</p>\n<p dir="auto">4. Recibir un masaje es una excelente manera de reconectarse con usted mismo y con otras personas que tambi\u00e9n podr\u00edan estar recibiendo uno, lo que le permitir\u00e1 sentirse m\u00e1s conectado con el mundo que lo rodea y lo har\u00e1 sentir menos solo o aislado.</p>\n<p dir="auto">5. Recibir un masaje lo ayudar\u00e1 a dormir mejor porque reduce las hormonas del estr\u00e9s que interfieren con los patrones de sue\u00f1o y libera la tensi\u00f3n en los m\u00fasculos que impide que el sue\u00f1o profundo se produzca de manera adecuada.</p>\n<h3 dir="auto">\u00bfLa aromaterapia ayuda a aliviar el estr\u00e9s? C\u00f3mo funciona y los mejores aromas para usar</h3>\n<p>&nbsp;</p>\n<p dir="auto">La aromaterapia es una terapia natural y hol\u00edstica que utiliza las propiedades terap\u00e9uticas de los aceites vegetales para ayudar a las personas a relajarse, reducir el estr\u00e9s y mejorar su estado de \u00e1nimo.</p>\n<p dir="auto">Diferentes olores tienen diferentes efectos en el cuerpo. Algunos son calmantes mientras que otros son energizantes. Los aromas m\u00e1s populares para la aromaterapia son la lavanda, los c\u00edtricos y la menta.</p>\n<p>El masaje relajante consiste en la realizaci\u00f3n de maniobras superficiales en las que la intensidad de la presi\u00f3n es suave. De manera que al recibir un contacto repetido y constante, se pierde la sensaci\u00f3n de dolor y los m\u00fasculos se relajan. El masaje relajante bogota viene con exfoliaci\u00f3n corporal, mascarilla hidratante, aromaterapia, musico terapia y decoraci\u00f3n especial.</p>\n<p>El Masaje Relajante bogota es una terapia manual destinada a mejorar el bienestar de la persona, ya que su m\u00e1ximo objetivo es aumentar la producci\u00f3n de endorfinas en nuestro cuerpo para conseguir bienestar.</p>\n',
    short_description:
      "<p>El masaje relajante consiste en la realizaci\u00f3n de maniobras superficiales en las que la intensidad de la presi\u00f3n es suave. De manera que al recibir un contacto repetido y constante, se pierde la sensaci\u00f3n de dolor y los m\u00fasculos se relajan.</p>\n<p>El Masaje Relajante bogota es una terapia manual destinada a mejorar el bienestar de la persona, ya que su m\u00e1ximo objetivo es aumentar la producci\u00f3n de endorfinas en nuestro cuerpo para conseguir alivio y descanso.</p>\n",
    sku: "",
    price: "278000",
    regular_price: "337000",
    sale_price: "278000",
    date_on_sale_from: null,
    date_on_sale_from_gmt: null,
    date_on_sale_to: null,
    date_on_sale_to_gmt: null,
    on_sale: true,
    purchasable: true,
    total_sales: 0,
    virtual: false,
    downloadable: false,
    downloads: [],
    download_limit: -1,
    download_expiry: -1,
    external_url: "",
    button_text: "",
    tax_status: "taxable",
    tax_class: "",
    manage_stock: false,
    stock_quantity: null,
    backorders: "no",
    backorders_allowed: false,
    backordered: false,
    low_stock_amount: null,
    sold_individually: false,
    weight: "",
    dimensions: { length: "", width: "", height: "" },
    shipping_required: true,
    shipping_taxable: true,
    shipping_class: "",
    shipping_class_id: 0,
    reviews_allowed: true,
    average_rating: "0.00",
    rating_count: 0,
    upsell_ids: [],
    cross_sell_ids: [],
    parent_id: 0,
    purchase_note: "",
    categories: [
      { id: 31, name: "Centro de belleza", slug: "centro-belleza-bogota" },
      {
        id: 84,
        name: "Masaje relajante en bogota a domicilio",
        slug: "masaje-relajante-bogota-domicilio",
      },
      { id: 100, name: "Spa en bogota", slug: "spa-en-bogota" },
    ],
    tags: [],
    images: [
      {
        id: 6393,
        date_created: "2022-06-06T08:36:13",
        date_created_gmt: "2022-06-06T18:36:13",
        date_modified: "2022-09-16T05:07:16",
        date_modified_gmt: "2022-09-16T15:07:16",
        src: "https://calyaan.com/wp-content/uploads/2022/06/Recurso-5-.jpg",
        name: "CALYAAN WEBSITE",
        alt: "Masaje relajante",
      },
    ],
    attributes: [],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 68,
    price_html:
      '<del aria-hidden="true"><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>337.000</bdi></span></del> <ins><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>278.000</bdi></span></ins>',
    related_ids: [818, 837, 841, 866, 860],
    meta_data: [
      { id: 109882, key: "rank_math_internal_links_processed", value: "1" },
      { id: 109902, key: "_wa_order_phone_number", value: "numero de calyaan" },
      { id: 109903, key: "_wa_order_button_text", value: "" },
      { id: 109904, key: "_wa_order_custom_message", value: "" },
      { id: 109905, key: "_hide_wa_button", value: "no" },
      { id: 109906, key: "_hide_atc_button", value: "no" },
      { id: 109907, key: "_force_show_atc_button", value: "no" },
      { id: 109908, key: "_product_meta_id", value: "0" },
      { id: 109909, key: "_wc_facebook_sync_enabled", value: "yes" },
      { id: 109910, key: "fb_visibility", value: "yes" },
      { id: 109911, key: "fb_product_description", value: "" },
      {
        id: 109912,
        key: "_wc_facebook_product_image_source",
        value: "product",
      },
      { id: 109913, key: "_wc_facebook_commerce_enabled", value: "no" },
      { id: 109914, key: "fb_product_group_id", value: "4312307765533600" },
      { id: 109915, key: "fb_product_item_id", value: "4312307782200265" },
      { id: 109916, key: "site-sidebar-layout", value: "default" },
      { id: 109917, key: "site-content-layout", value: "default" },
      { id: 109918, key: "theme-transparent-header-meta", value: "default" },
      { id: 109919, key: "stick-header-meta", value: "default" },
      { id: 109920, key: "_yoast_wpseo_primary_product_cat", value: "31" },
      { id: 109921, key: "_yoast_wpseo_content_score", value: "90" },
      {
        id: 109922,
        key: "_yoast_wpseo_estimated-reading-time-minutes",
        value: "1",
      },
      { id: 109923, key: "pi_dcw_product_redirect", value: "0" },
      { id: 109924, key: "pi_dcw_product_overwrite_global", value: "0" },
      { id: 109925, key: "pi_dcw_product_redirect_to_page", value: "" },
      { id: 109926, key: "new_tab", value: "1" },
      { id: 109927, key: "_catcbll_btn_label", value: [""] },
      { id: 109928, key: "_catcbll_btn_link", value: [""] },
      {
        id: 109929,
        key: "_yoast_wpseo_focuskw",
        value: "Masaje relajante en bogota a domicilio",
      },
      {
        id: 109930,
        key: "_yoast_wpseo_metadesc",
        value:
          "El Masaje Relajante en bogota a domicilio esta destinada a mejorar el bienestar de la persona aumentando la producci\u00f3n de endorfinas.",
      },
      { id: 109931, key: "_yoast_wpseo_linkdex", value: "42" },
      { id: 109932, key: "mwb_product_points_enable", value: "no" },
      { id: 109933, key: "mwb_points_product_value", value: "" },
      { id: 109934, key: "_last_editor_used_jetpack", value: "classic-editor" },
      { id: 109935, key: "_yoast_wpseo_wordproof_timestamp", value: "" },
      { id: 109936, key: "rank_math_analytic_object_id", value: "2783" },
      { id: 109937, key: "rank_math_seo_score", value: "89" },
      { id: 109938, key: "rank_math_focus_keyword", value: "masaje relajante" },
      { id: 109939, key: "_rank_math_gtin_code", value: "" },
      { id: 109940, key: "rank_math_internal_links_processed", value: "1" },
      { id: 109941, key: "rank_math_primary_product_cat", value: "0" },
      {
        id: 109942,
        key: "links_for_sold",
        value:
          '"https://api.whatsapp.com/send/?phone=573147428757&text&type=phone_number&app_absent=0"',
      },
    ],
    stock_status: "instock",
    has_options: false,
    _links: {
      self: [{ href: "https://calyaan.com/wp-json/wc/v3/products/12303" }],
      collection: [{ href: "https://calyaan.com/wp-json/wc/v3/products" }],
    },
  },
  {
    id: 12301,
    name: "Limpieza facial profunda + Masaje descontracturante",
    slug: "limpieza-facial-profunda-masaje-descontracturante",
    permalink:
      "https://calyaan.com/producto/limpieza-facial-profunda-masaje-descontracturante/",
    date_created: "2023-05-10T22:11:47",
    date_created_gmt: "2023-05-11T03:11:47",
    date_modified: "2023-05-10T22:14:07",
    date_modified_gmt: "2023-05-11T03:14:07",
    type: "simple",
    status: "publish",
    featured: false,
    catalog_visibility: "visible",
    description:
      "<p>*La limpieza facial profunda a domicilio* es un procedimiento de mantenimiento que elimina todas las impurezas que se encuentran en la piel generadas por el mismo cuerpo y por el ambiente, estas impurezas son el origen de imperfecciones, acn\u00e9, arrugas prematuras y p\u00e9rdida de brillo.</p>\n<p>Una limpieza facial profunda recupera la luminosidad y uniformidad de tu cara. Aprende sobre c\u00f3mo la limpieza facial evita imperfecciones por acn\u00e9 y arrugas y sobre los diferentes tratamientos de limpieza facial que puedes hacer en casa o con una limpieza facial profesional.</p>\n<h2><strong>Hazte regularmente una limpieza facial para que la grasa, la contaminaci\u00f3n o el maquillaje no te roben los a\u00f1os</strong></h2>\n<p>&nbsp;</p>\n<p>La suciedad, la contaminaci\u00f3n ambiental, la grasa, el maquillaje, el clima e incluso el estr\u00e9s son algunos factores que hacen que la piel\u00a0<strong>pierda higiene</strong>\u00a0y con ella toda\u00a0<strong>vitalidad y luminosidad.</strong></p>\n<p>&nbsp;</p>\n<p><strong>Lucir radiante</strong>\u00a0con una\u00a0<strong>cara uniforme</strong>\u00a0y\u00a0<strong>luminosa</strong>\u00a0es importante para esas fotos especiales y citas importantes donde quieres destacarte y llamar la atenci\u00f3n.</p>\n",
    short_description:
      "<p>*La limpieza facial profunda a domicilio* es un procedimiento de mantenimiento que elimina todas las impurezas que se encuentran en la piel generadas por el mismo cuerpo y por el ambiente, estas impurezas son el origen de imperfecciones, acn\u00e9, arrugas prematuras y p\u00e9rdida de brillo.</p>\n",
    sku: "",
    price: "278000",
    regular_price: "395000",
    sale_price: "278000",
    date_on_sale_from: null,
    date_on_sale_from_gmt: null,
    date_on_sale_to: null,
    date_on_sale_to_gmt: null,
    on_sale: true,
    purchasable: true,
    total_sales: 0,
    virtual: false,
    downloadable: false,
    downloads: [],
    download_limit: -1,
    download_expiry: -1,
    external_url: "",
    button_text: "",
    tax_status: "taxable",
    tax_class: "",
    manage_stock: false,
    stock_quantity: null,
    backorders: "no",
    backorders_allowed: false,
    backordered: false,
    low_stock_amount: null,
    sold_individually: false,
    weight: "",
    dimensions: { length: "", width: "", height: "" },
    shipping_required: true,
    shipping_taxable: true,
    shipping_class: "",
    shipping_class_id: 0,
    reviews_allowed: true,
    average_rating: "0.00",
    rating_count: 0,
    upsell_ids: [],
    cross_sell_ids: [],
    parent_id: 0,
    purchase_note: "",
    categories: [
      { id: 31, name: "Centro de belleza", slug: "centro-belleza-bogota" },
      {
        id: 84,
        name: "Masaje relajante en bogota a domicilio",
        slug: "masaje-relajante-bogota-domicilio",
      },
      { id: 100, name: "Spa en bogota", slug: "spa-en-bogota" },
    ],
    tags: [],
    images: [
      {
        id: 9303,
        date_created: "2022-09-16T05:15:00",
        date_created_gmt: "2022-09-16T15:15:00",
        date_modified: "2022-09-16T05:18:18",
        date_modified_gmt: "2022-09-16T15:18:18",
        src: "https://calyaan.com/wp-content/uploads/2022/09/11-300x300-1.png",
        name: "11-300&#215;300",
        alt: "Limpieza facial profunda",
      },
    ],
    attributes: [],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 9,
    price_html:
      '<del aria-hidden="true"><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>395.000</bdi></span></del> <ins><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>278.000</bdi></span></ins>',
    related_ids: [865, 799, 860, 830, 834],
    meta_data: [
      { id: 109819, key: "rank_math_internal_links_processed", value: "1" },
      { id: 109839, key: "_wa_order_phone_number", value: "numero de calyaan" },
      { id: 109840, key: "_wa_order_button_text", value: "" },
      { id: 109841, key: "_wa_order_custom_message", value: "" },
      { id: 109842, key: "_hide_wa_button", value: "no" },
      { id: 109843, key: "_hide_atc_button", value: "no" },
      { id: 109844, key: "_force_show_atc_button", value: "no" },
      { id: 109845, key: "_product_meta_id", value: "0" },
      { id: 109846, key: "_wc_facebook_sync_enabled", value: "yes" },
      { id: 109847, key: "fb_visibility", value: "yes" },
      { id: 109848, key: "fb_product_description", value: "" },
      {
        id: 109849,
        key: "_wc_facebook_product_image_source",
        value: "product",
      },
      { id: 109850, key: "_wc_facebook_commerce_enabled", value: "no" },
      { id: 109851, key: "fb_product_group_id", value: "6102064246535365" },
      { id: 109852, key: "fb_product_item_id", value: "6102064283202028" },
      { id: 109853, key: "site-sidebar-layout", value: "default" },
      { id: 109854, key: "site-content-layout", value: "default" },
      { id: 109855, key: "theme-transparent-header-meta", value: "default" },
      { id: 109856, key: "stick-header-meta", value: "default" },
      { id: 109857, key: "_yoast_wpseo_primary_product_cat", value: "31" },
      { id: 109858, key: "_yoast_wpseo_content_score", value: "90" },
      {
        id: 109859,
        key: "_yoast_wpseo_estimated-reading-time-minutes",
        value: "1",
      },
      { id: 109860, key: "pi_dcw_product_redirect", value: "0" },
      { id: 109861, key: "pi_dcw_product_overwrite_global", value: "0" },
      { id: 109862, key: "pi_dcw_product_redirect_to_page", value: "" },
      { id: 109863, key: "new_tab", value: "1" },
      { id: 109864, key: "_catcbll_btn_label", value: [""] },
      { id: 109865, key: "_catcbll_btn_link", value: [""] },
      {
        id: 109866,
        key: "_yoast_wpseo_focuskw",
        value: "Limpieza facial profunda",
      },
      {
        id: 109867,
        key: "_yoast_wpseo_metadesc",
        value:
          "La limpieza facial profunda. Es un procedimiento de mantenimiento que elimina todas las impurezas que se encuentran en la piel.",
      },
      { id: 109868, key: "_yoast_wpseo_linkdex", value: "53" },
      { id: 109869, key: "mwb_product_points_enable", value: "no" },
      { id: 109870, key: "mwb_points_product_value", value: "" },
      { id: 109871, key: "_last_editor_used_jetpack", value: "classic-editor" },
      { id: 109872, key: "_yoast_wpseo_wordproof_timestamp", value: "" },
      { id: 109873, key: "rank_math_analytic_object_id", value: "2782" },
      { id: 109874, key: "rank_math_seo_score", value: "85" },
      {
        id: 109875,
        key: "rank_math_focus_keyword",
        value: "Limpieza facial profunda",
      },
      { id: 109876, key: "_rank_math_gtin_code", value: "" },
      { id: 109877, key: "rank_math_internal_links_processed", value: "1" },
      { id: 109878, key: "rank_math_primary_product_cat", value: "0" },
      {
        id: 109879,
        key: "links_for_sold",
        value:
          '"https://api.whatsapp.com/send/?phone=573147428757&text&type=phone_number&app_absent=0"',
      },
    ],
    stock_status: "instock",
    has_options: false,
    _links: {
      self: [{ href: "https://calyaan.com/wp-json/wc/v3/products/12301" }],
      collection: [{ href: "https://calyaan.com/wp-json/wc/v3/products" }],
    },
  },
  {
    id: 11660,
    name: "Drenaje linf\u00e1tico x 10 sesiones",
    slug: "drenaje-linfatico",
    permalink: "https://calyaan.com/producto/drenaje-linfatico/",
    date_created: "2023-04-04T23:52:56",
    date_created_gmt: "2023-04-05T04:52:56",
    date_modified: "2023-05-13T23:55:40",
    date_modified_gmt: "2023-05-14T04:55:40",
    type: "simple",
    status: "publish",
    featured: false,
    catalog_visibility: "visible",
    description:
      "<p>El Drenaje linf\u00e1tico\u00a0<strong>es sin camilla. </strong>T\u00e9cnica de masoterapia que se engloba en los campos de la fisioterapia y la medicina alternativa es un tipo de masaje suave y ligero que se aplica sobre el sistema circulatorio cuyo objetivo es movilizar los l\u00edquidos del organismo para favorecer la eliminaci\u00f3n de las sustancias y obtener mayor alivio.</p>\n<p>El Drenaje linf\u00e1tico es una t\u00e9cnica de masoterapia que se engloba en los campos de la fisioterapia y la medicina alternativa es un tipo de masaje suave y ligero que se aplica sobre el sistema circulatorio cuyo objetivo es movilizar los l\u00edquidos del organismo para favorecer la eliminaci\u00f3n de las sustancias y obtener mayor alivio.</p>\n<p>El<strong>\u00a0drenaje linf\u00e1tico</strong>\u00a0es un masaje que act\u00faa sobre los vasos linf\u00e1ticos con el fin de<strong>\u00a0eliminar el l\u00edquido intersticial y linf\u00e1tico</strong>.</p>\n<p>Gracias a su acci\u00f3n antiedematosa y analg\u00e9sica sobre las fibras musculares lisas, el drenaje linf\u00e1tico est\u00e1 especialmente indicado para atenuar el llamado efecto piel de naranja de la celulitis y para tratar edemas postquir\u00fargicos o cicatrices.</p>\n<p>En cuanto al efecto sobre las fibras musculares estriadas, este drenaje se propone a los pacientes por su efecto relajante, especialmente en el caso de m\u00fasculos tensos o hipert\u00f3nicos.</p>\n<p>En general, el drenaje linf\u00e1tico aumenta la respuesta del sistema inmunol\u00f3gico,\u00a0<strong>mejorando as\u00ed la respuesta del sistema de defensa</strong>\u00a0en las zonas tratadas con este masaje.</p>\n",
    short_description:
      "<p>El Drenaje linf\u00e1tico <strong>es sin camilla. </strong>T\u00e9cnica de masoterapia que se engloba en los campos de la fisioterapia y la medicina alternativa es un tipo de masaje suave y ligero que se aplica sobre el sistema circulatorio cuyo objetivo es movilizar los l\u00edquidos del organismo para favorecer la eliminaci\u00f3n de las sustancias y obtener mayor alivio.</p>\n<p>El Drenaje linf\u00e1tico es una t\u00e9cnica de masoterapia que se engloba en los campos de la fisioterapia y la medicina alternativa es un tipo de masaje suave y ligero que se aplica sobre el sistema circulatorio cuyo objetivo es movilizar los l\u00edquidos del organismo para favorecer la eliminaci\u00f3n de las sustancias y obtener mayor alivio.</p>\n",
    sku: "",
    price: "990000",
    regular_price: "1500000",
    sale_price: "990000",
    date_on_sale_from: null,
    date_on_sale_from_gmt: null,
    date_on_sale_to: null,
    date_on_sale_to_gmt: null,
    on_sale: true,
    purchasable: true,
    total_sales: 0,
    virtual: false,
    downloadable: false,
    downloads: [],
    download_limit: -1,
    download_expiry: -1,
    external_url: "",
    button_text: "",
    tax_status: "taxable",
    tax_class: "",
    manage_stock: false,
    stock_quantity: null,
    backorders: "no",
    backorders_allowed: false,
    backordered: false,
    low_stock_amount: null,
    sold_individually: false,
    weight: "",
    dimensions: { length: "", width: "", height: "" },
    shipping_required: true,
    shipping_taxable: true,
    shipping_class: "",
    shipping_class_id: 0,
    reviews_allowed: true,
    average_rating: "5.00",
    rating_count: 46,
    upsell_ids: [],
    cross_sell_ids: [],
    parent_id: 0,
    purchase_note: "",
    categories: [
      { id: 31, name: "Centro de belleza", slug: "centro-belleza-bogota" },
      {
        id: 84,
        name: "Masaje relajante en bogota a domicilio",
        slug: "masaje-relajante-bogota-domicilio",
      },
    ],
    tags: [],
    images: [
      {
        id: 8985,
        date_created: "2022-06-20T15:52:16",
        date_created_gmt: "2022-06-21T01:52:16",
        date_modified: "2022-06-20T15:52:30",
        date_modified_gmt: "2022-06-21T01:52:30",
        src: "https://calyaan.com/wp-content/uploads/2022/06/close-up-abdomen-massage-concept-scaled-1.jpg",
        name: "masajes reductivos de abdomen y cintura,",
        alt: "masajes reductivos de abdomen y cintura,",
      },
    ],
    attributes: [],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 43,
    price_html:
      '<del aria-hidden="true"><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>1.500.000</bdi></span></del> <ins><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>990.000</bdi></span></ins>',
    related_ids: [795, 865, 828, 841, 826],
    meta_data: [
      { id: 103535, key: "rank_math_internal_links_processed", value: "1" },
      { id: 103536, key: "rank_math_seo_score", value: "87" },
      {
        id: 103537,
        key: "rank_math_focus_keyword",
        value: "drenaje linfatico",
      },
      { id: 103538, key: "_rank_math_gtin_code", value: "" },
      { id: 103557, key: "rank_math_primary_product_cat", value: "31" },
      { id: 103558, key: "rank_math_analytic_object_id", value: "2776" },
    ],
    stock_status: "instock",
    has_options: false,
    _links: {
      self: [{ href: "https://calyaan.com/wp-json/wc/v3/products/11660" }],
      collection: [{ href: "https://calyaan.com/wp-json/wc/v3/products" }],
    },
  },
  {
    id: 11659,
    name: "Carboxiterapia x 5 sesiones (no disponible)",
    slug: "carboxiterapia",
    permalink: "https://calyaan.com/producto/carboxiterapia/",
    date_created: "2023-04-04T23:39:03",
    date_created_gmt: "2023-04-05T04:39:03",
    date_modified: "2023-05-15T14:58:22",
    date_modified_gmt: "2023-05-15T19:58:22",
    type: "simple",
    status: "publish",
    featured: false,
    catalog_visibility: "visible",
    description:
      "<p>Carboxiterapia es un procedimiento no quir\u00fargico para tratar celulitis, grasa localizada, flacidez y estr\u00edas. Consiste en el uso terap\u00e9utico de di\u00f3xido de carbono en forma subcut\u00e1nea, sin ning\u00fan efecto negativo para la salud del paciente.</p>\n<p>Tambi\u00e9n es utilizada como tratamiento postoperatorio de la liposucci\u00f3n o cirug\u00edas est\u00e9ticas para corregir irregularidades de la piel, prevenir fibrosis y mejorar los resultados de dicho procedimiento.</p>\n<h2>\u00bfCuando no aplicar Carboxiterapia?</h2>\n<p>La aplicaci\u00f3n de di\u00f3xido de carbono est\u00e9ril es una t\u00e9cnica que no ha dejado de ser tendencia, siendo de gran beneficio para combatir la flacidez cut\u00e1nea y reducir las c\u00e9lulas adiposas en el cuerpo, con el fin de obtener una p\u00e9rdida de peso.</p>\n<p>Sin embargo, este tratamiento est\u00e9tico no es recomendado en ciertas ocasiones. Disfrutar sus ventaja para eliminar la grasa y mejorar la tersura de la piel, no podr\u00e1 ser disfrutando cuando</p>\n<ul>\n<li>Personas asm\u00e1ticas.</li>\n<li>Pacientes de insufici\u00eancia card\u00edaca, arritmias e problemas coron\u00e1rios.</li>\n<li>Quien padece de insuficiencia renal o hep\u00e1tica.</li>\n<li>Personas epil\u00e9pticas.</li>\n<li>Con alguna afecci\u00f3n cut\u00e1nea</li>\n<li>Quien est\u00e9 bajo el f\u00e1rmaco Acetazolamida o anticoagulantes en general.</li>\n<li>Las personas que tengan flebitis o gangrena.</li>\n<li>S\u00edntomas de resfriado o tos</li>\n<li>Durante el embarazo ni en el tiempo de lactancia</li>\n<li>En el caso de estar en ciclo f\u00e9rtil menstrual</li>\n</ul>\n<p>&nbsp;</p>\n<p>Es importante la comunicaci\u00f3n con los especialistas que realizan carboxiterapia quienes deber\u00e1n hacer las preguntas pertinentes para descartar a las personas con alguno de estos perfiles, puesto la aplicaci\u00f3n de este tratamiento puede ser contraproducente para ellos.</p>\n",
    short_description:
      "<p>Carboxiterapia es un procedimiento no quir\u00fargico para tratar celulitis, grasa localizada, flacidez y estr\u00edas. Consiste en el uso terap\u00e9utico de di\u00f3xido de carbono en forma subcut\u00e1nea, sin ning\u00fan efecto negativo para la salud del paciente.</p>\n<p>Tambi\u00e9n es utilizada como tratamiento postoperatorio de la liposucci\u00f3n o cirug\u00edas est\u00e9ticas para corregir irregularidades de la piel, prevenir fibrosis y mejorar los resultados de dicho procedimiento.</p>\n<h2>\u00bfCuando no aplicar Carboxiterapia?</h2>\n<p>La aplicaci\u00f3n de di\u00f3xido de carbono est\u00e9ril es una t\u00e9cnica que no ha dejado de ser tendencia, siendo de gran beneficio para combatir la flacidez cut\u00e1nea y reducir las c\u00e9lulas adiposas en el cuerpo, con el fin de obtener una p\u00e9rdida de peso.</p>\n<p>Sin embargo, este tratamiento est\u00e9tico no es recomendado en ciertas ocasiones. Disfrutar sus ventaja para eliminar la grasa y mejorar la tersura de la piel, no podr\u00e1 ser disfrutando cuando</p>\n<ul>\n<li>Personas asm\u00e1ticas.</li>\n<li>Pacientes de insufici\u00eancia card\u00edaca, arritmias e problemas coron\u00e1rios.</li>\n<li>Quien padece de insuficiencia renal o hep\u00e1tica.</li>\n<li>Personas epil\u00e9pticas.</li>\n<li>Con alguna afecci\u00f3n cut\u00e1nea</li>\n<li>Quien est\u00e9 bajo el f\u00e1rmaco Acetazolamida o anticoagulantes en general.</li>\n<li>Las personas que tengan flebitis o gangrena.</li>\n<li>S\u00edntomas de resfriado o tos</li>\n<li>Durante el embarazo ni en el tiempo de lactancia</li>\n<li>En el caso de estar en ciclo f\u00e9rtil menstrual</li>\n</ul>\n<p>&nbsp;</p>\n<p>Es importante la comunicaci\u00f3n con los especialistas que realizan carboxiterapia quienes deber\u00e1n hacer las preguntas pertinentes para descartar a las personas con alguno de estos perfiles, puesto la aplicaci\u00f3n de este tratamiento puede ser contraproducente para ellos.</p>\n",
    sku: "",
    price: "650000",
    regular_price: "900000",
    sale_price: "650000",
    date_on_sale_from: null,
    date_on_sale_from_gmt: null,
    date_on_sale_to: null,
    date_on_sale_to_gmt: null,
    on_sale: true,
    purchasable: true,
    total_sales: 0,
    virtual: false,
    downloadable: false,
    downloads: [],
    download_limit: -1,
    download_expiry: -1,
    external_url: "",
    button_text: "",
    tax_status: "taxable",
    tax_class: "",
    manage_stock: true,
    stock_quantity: 0,
    backorders: "no",
    backorders_allowed: false,
    backordered: false,
    low_stock_amount: null,
    sold_individually: false,
    weight: "",
    dimensions: { length: "", width: "", height: "" },
    shipping_required: true,
    shipping_taxable: true,
    shipping_class: "",
    shipping_class_id: 0,
    reviews_allowed: true,
    average_rating: "0.00",
    rating_count: 0,
    upsell_ids: [],
    cross_sell_ids: [],
    parent_id: 0,
    purchase_note: "",
    categories: [
      { id: 31, name: "Centro de belleza", slug: "centro-belleza-bogota" },
      {
        id: 84,
        name: "Masaje relajante en bogota a domicilio",
        slug: "masaje-relajante-bogota-domicilio",
      },
    ],
    tags: [],
    images: [
      {
        id: 8964,
        date_created: "2022-06-20T09:52:06",
        date_created_gmt: "2022-06-20T19:52:06",
        date_modified: "2022-06-20T09:52:35",
        date_modified_gmt: "2022-06-20T19:52:35",
        src: "https://calyaan.com/wp-content/uploads/2022/06/woman-receiving-abdomen-massage-in-spa-wellness-center.jpg",
        name: "masajes reductivos",
        alt: "masajes reductivos",
      },
    ],
    attributes: [],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 19,
    price_html:
      '<del aria-hidden="true"><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>900.000</bdi></span></del> <ins><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>650.000</bdi></span></ins>',
    related_ids: [860, 839, 801, 866, 841],
    meta_data: [
      { id: 103505, key: "rank_math_internal_links_processed", value: "1" },
      { id: 103506, key: "rank_math_seo_score", value: "87" },
      {
        id: 103507,
        key: "rank_math_contentai_score",
        value: {
          wordCount: "100",
          linkCount: "0",
          headingCount: "100",
          mediaCount: "62.22",
        },
      },
      { id: 103508, key: "rank_math_focus_keyword", value: "carboxiterapia" },
      { id: 103509, key: "_rank_math_gtin_code", value: "" },
      { id: 103527, key: "rank_math_primary_product_cat", value: "31" },
      { id: 103528, key: "rank_math_analytic_object_id", value: "2775" },
    ],
    stock_status: "outofstock",
    has_options: false,
    _links: {
      self: [{ href: "https://calyaan.com/wp-json/wc/v3/products/11659" }],
      collection: [{ href: "https://calyaan.com/wp-json/wc/v3/products" }],
    },
  },
];


  try {
    await data.map(async (productoState) => {
      let producto = await new Producto({
        nombre: productoState.name,
        idWP: productoState.id,
        img: productoState.images[0].src,
        descripcion: productoState.short_description,
        precio: productoState.price,
        precio_regular: productoState.regular_price,
        link: productoState.permalink
      });

      await producto.save();
    });

    const allProductos =  await Producto.find()

    return res.json(allProductos);
  } catch (error) {
    console.log(error);
  }
};

export { cargarProductosWP };
